### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TaekSoonJang** [druid-io/druid-io.github.io#112]
Please refer to attached image files.

There is a broken link at documentation page of 'Tutorial : The Druid Cluster'
![druid_broken_link](https://cloud.githubusercontent.com/assets/3775233/7040075/4e1ced2e-de05-11e4-940f-1a521f01866a.png)
![druid_cluster](https://cloud.githubusercontent.com/assets/3775233/7040076/4e1cd5f0-de05-11e4-8bcb-6958c7873efa.png)

**Comment by textractor** [comment]
Those are not the pages you are looking for. :octocat:

Things have changed a bit. Currently for Druid 0.7, start [here](http://druid.io/docs/latest/Tutorial:-A-First-Look-at-Druid.html) and look at the tutorials listed on the right-hand side.

**Comment by textractor** [comment]
P.S. That broken link should point to Loading Streaming Data. Will fix shortly.

**Comment by fjy** [comment]
Closing this issue as I believe things have been fixed.
