### ISSUE TITLE
Make accessing old documentation easier

### ISSUE THREAD

**Issue by anshbansal** [druid-io/druid-io.github.io#151]
I was trying to access old documentation specififically for 0.6.142. I tried changing the number in the current home page http://druid.io/docs/0.8.0/design/index.html but wasn't able to get to the docs.

Then I found this repo and saw the structure. I was able to find the link http://druid.io/docs/0.6.142/index.html. 
But it would be better to have a link for accessing all versions of docs. Or perhaps redirects can be added from the base url http://druid.io/docs/0.6.142/ to http://druid.io/docs/0.6.142/index.html.

I think the first option is better but whatever seems better to you.

**Comment by fjy** [comment]
I am closing this issue as the docs have maintained a pretty consistent structure over the last few versions.

**Comment by giorgosp** [comment]
I am looking for the 0.16.1 druid docs but can't find them. I have tried druid.io/docs/0.16,1/ but it returns 404.
What led me here is that for the kafka ingestion spec, the `parseSpec` json key is not needed anymore but it is required in the 0.16.1 version. There is no error if not provided. The task is registered and displayed in the supervisors section of the ui but there aren't any active tasks created for it.

Would be great if there were documentation links for each Druid version.
