### ISSUE TITLE
Update zookeeper version in tutorial example

### ISSUE THREAD

**Issue by AdrieanKhisbe** [druid-io/druid-io.github.io#193]
Current tutorial about druid point a zookeper version not available.

should be adapted to :

```sh
 curl http://www.gtlib.gatech.edu/pub/apache/zookeeper/zookeeper-3.4.7/zookeeper-3.4.7.tar.gz -o zookeeper-3.4.7.tar.gz
  tar xzf zookeeper-3.4.7.tar.gz
  cd zookeeper-3.4.7
  cp conf/zoo_sample.cfg conf/zoo.cfg
  ./bin/zkServer.sh start
  cd ..
```

:)

**Comment by himanshug** [comment]
would you like to send a PR to fix this? its an easy way to contribute.
original file is located at https://github.com/druid-io/druid/blob/master/docs/content/tutorials/tutorial-a-first-look-at-druid.md .

**Comment by AdrieanKhisbe** [comment]
voilà :)
