### ISSUE TITLE
Can you please add Smart Bid

### ISSUE THREAD

**Issue by smartbidpay** [druid-io/druid-io.github.io#365]
Smart Bid

Smart Bid is a unique marketing solution platform empowering advertising teams.
A one-stop shop taking advantage of proprietary technology to analyze and reach the right audience with the right creative at the right time. We use Druid to gain real-time insights on real time bidding using our machine learning algorithms.

**Comment by fjy** [comment]
Thanks @smartbidpay. We will add it.
