### ISSUE TITLE
Misleading title of a page

### ISSUE THREAD

**Issue by leventov** [druid-io/druid-io.github.io#416]
google "site:druid.io/docs/latest/Tasks.html" and you will see that the title of this page is displayed as "Hadoop Index Task", that could be very misleading for some who search for Druid docs

**Comment by drcrallen** [comment]
`https://www.google.com/search?q=site%3Adruid.io%2Fdocs%2Flatest%2FTasks.html` for reference

**Comment by LautaroLobo12** [comment]
On the contributing.md file says:

>For any documentation changes (in the "docs" folder), please submit pull requests to the main >ruid repo. All Druid documentation is hosted under https://github.com/apache/incubator-druid/tree/master/docs/content.

So, I think that this issue deserves to be closed.

**Comment by leventov** [comment]
This issue should be closed, indeed, but for a different reason: it appears to be fixed in https://druid.apache.org/docs/. There is no page with the title "Hadoop Index Task" now.
