### ISSUE TITLE
"Build from Source" page states an outdated JDK version 7

### ISSUE THREAD

**Issue by yurmix** [druid-io/druid-io.github.io#470]
### Problem:
The page `src/docs/latest/development/build.md` (Title: [Build from Source](http://druid.io/docs/latest/development/build.html)) states the following:
> Building Druid requires the following: - JDK 7 or JDK 8

While in fact pom.xml mandates JDK 8 since version 0.10.0 (as evident in [Druid pr #3914](https://github.com/apache/incubator-druid/pull/3914)).

### Solution:
Remove the text "JDK 7 or ".

**Comment by yurmix** [comment]
I am going pause here and create a pull request on the main Druid repo. 
Would you want to fix documentation from 0.10.0 onwards as well?
If so then I'll create a pull request for this repo as well.

**Comment by jihoonson** [comment]
Thanks @yurmix. I think it's fine to not fix old docs.
