### ISSUE TITLE
Incomplete webpage titles

### ISSUE THREAD

**Issue by OItsMAK** [druid-io/druid-io.github.io#545]
[Many](http://druid.io/docs/latest/development/integrating-druid-with-other-technologies.html) [many](http://druid.io/docs/latest/ingestion/native-batch.html) [many](http://druid.io/docs/latest/design/) pages of the Docs have incomplete titles;

they all have this in HTML header:
```HTML
 <title>Druid | </title>
```

Yet many pages like [this one](http://druid.io/community/) have correct titles.

This makes exploring the website in many tabs hard.

**Comment by OItsMAK** [comment]
From what i have learned, all these pages are missing titles in their relative .md files. 
I'll write some code to add such lines to all of them and create a pull request when i find some free time.

I gotta ask tho, is this intentional? because an old version i checked (not latest) also had the same problem.

**Comment by gianm** [comment]
It's not intentional, looks like an oversight to me.

**Comment by OItsMAK** [comment]
@vogievetsky 
Just recently I noticed it's working. (Couldn't see the changes right after your PR being merged.), cheers! 👍
